version: "3.8"
services:
  xgproyect-v3:
    build:
      context: .
      args:
        PHP_VERSION: 7.3
    container_name: xgproyect-v3
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - ./src/upload:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 127.0.0.1:33060:3306 # change ip if required
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: xgp
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8081:80"
    environment:
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: db
